Don't sort an empty file list
kartotherian/tilerator-jobprocessor pull request #2
Opened 2017-01-31 22:48 UTC by MaxSem

sort just waits for stdin forever

Closes #1

Bug: T145534

2017-02-03 20:51 UTC, nyurik requested changes

2017-02-03 20:51 UTC, nyurik commented on lib/fileParser.js
> +                core.log('info', 'All tiles filtered out, nothing to process');
I don't think catching and ignoring all errors is good. Its better to explicitly handle it by returning `false` or `null`, and handling it.

2017-02-10 23:36 UTC, MaxSem commented
Updated.

2017-02-12 06:10 UTC, nyurik commented
I'm a bit confused - you still throw an exception if the sort list is empty, but you handle it later too?

2017-02-13 20:37 UTC, MaxSem commented
The check in `sortFile()` is needed to prevent any reoccurences in the future - this function can still hang if called with empty list.

2017-02-14 22:03 UTC, MaxSem commented
Resolved by @nyurik in 4186abc5b2752c9ea5fccbb1dcb638502a572959.

2017-02-14 22:03 UTC, closed without merging